import tile

map = '''
.................
.................
.................
.................
.................
....xxxxxxxx.....
....x      xx....
....x       x....
....x      xx....
....x      x.....
....xxxxxxxx.....
.................
.................
.................
'''

map = [[tile.tiles[t]() for t in line]
       for line in map.splitlines() if line]
